FROM postgres:16

RUN apt-get update && apt-get install -y \
    postgis postgresql-16-postgis-3 \
 && rm -rf /var/lib/apt/lists/*

COPY ./docker-entrypoint-initdb.d/init_postgis.sh /docker-entrypoint-initdb.d/