version: '3.10'

services:
  backend:
    build: ./backend
    command: >
      sh -c "gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 2"
    volumes:
      - ./backend:/usr/src/app/
      - static_volume:/usr/src/app/api/static
      - media_volume:/usr/src/app/media
      - logs_volume:/usr/src/app/logs
    ports:
      - "8000:8000"
    depends_on:
      - db
      - migration
    networks:
      - backend

  db:
    image: postgis/postgis:16-3.4
    restart: always
    environment:
      POSTGRES_DB: kyrgeo
      POSTGRES_USER: bagyshan
      POSTGRES_PASSWORD: 1
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - backend
    
  migration:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: on-failure
    command: >
      sh -c "python manage.py makemigrations && python manage.py migrate"
    volumes:
      - ./backend:/usr/src/app/
    depends_on:
      - db
    networks:
      - backend

  celery:
    build: ./backend
    command: celery -A config worker -l info
    volumes: 
      - ./backend:/usr/src/app/
    depends_on:
      - backend
      - redis
    networks:
      - backend

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - backend

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "80:80"
    restart: always
    volumes:
      - static_volume:/usr/src/app/api/static
      - media_volume:/usr/src/app/media
    depends_on:
      - backend
    networks:
      - backend

  # frontend:
  #   build: ./frontend
  #   # command: npm start
  #   ports:
  #     - "80:80"
  #   tty: true
  #   volumes:
  #     - ./frontend/:/usr/src/app/
  #     - node_modules:/usr/src/app/node_modules
  #   depends_on:
  #     - backend
  #   networks:
  #     - backend



  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   restart: on-failure
  #   ports:
  #     - "80:80"
  #   container_name: "frontend"
  #   volumes:
  #     - front_static_volume:/usr/src/app/static
  #     - static_volume:/usr/src/app/api/static
  #   environment:
  #     - NODE_ENV=production
  #   depends_on:
  #     - backend
  #   networks:
  #     - backend


volumes:
  postgres_data:
  static_volume:
  front_static_volume:
  media_volume:
  logs_volume:

networks:
  backend: